language: node_js
node_js:
- 6.5.0
branches:
  except:
  - gh-pages
before_install:
- openssl aes-256-cbc -K $encrypted_773aed02da6c_key -iv $encrypted_773aed02da6c_iv
  -in id_rsa.enc -out id_rsa -d
after_sucess:
  - npm run gh-pages-travis
env:
  global:
    - SSH_KEY="id_rsa"
    - GIT_NAME="travis"
    - GIT_EMAIL="brycedneal@gmail.com"
    - SOURCE_DIR="static"
    - DEPLOY_BRANCH="master"