language: node_js
node_js:
- 6.5.0
branches:
  except:
  - gh-pages
script: npm install && npm run build
before_install:
  - npm install -g webpack@1.13.2
  - openssl aes-256-cbc -K $encrypted_773aed02da6c_key -iv $encrypted_773aed02da6c_iv
    -in id_rsa.enc -out id_rsa -d
env:
  global:
    - SSH_KEY="id_rsa"
    - GIT_NAME="travis"
    - SOURCE_DIR="./static"
    - DEPLOY_BRANCH="master"
after_success: ./deploy.sh